### ISSUE TITLE
Greetings demo extension link

### ISSUE THREAD

**Issue by thomastthai** [verifa/horizon#4]
In the Greetings demo, the `extension` link results in 404 error because the file doesn't exist.

**Comment by jlarfors** [comment]
@thomastthai thanks for reporting. This should be fixed now. There's A LOT of changes going on right now... I didn't expect people to find it just yet :) but great that you did.

I will add a mention in the README that please expect things to be broken.

**Comment by jlarfors** [comment]
On second inspection, I see what you mean with the link in the README. That needs fixing. I'll get it fixed shortly.

**Comment by thomastthai** [comment]
Thanks for fixing the broken link so fast. Horizon's development looks like it's moving along at a quick pace.

@gedw99 [mentioned on Reddit](https://www.reddit.com/r/golang/s/MvJq4t6D0G) that Horizon as a good example of NATS usage. That's how I found your work!

**Comment by jlarfors** [comment]
Great, and thanks for the reddit link.

I added a new issue to create a real http handler for the greetings demo now: https://github.com/verifa/horizon/issues/5
I'll get to it soon, so there is some example of how to do that.

I love NATS, and really this is just a wrapper over NATS. Whether it is through horizon or something else, I want to see more nats being used for internal platforms being built.

Happy to talk about what you're trying to do with nats/horizon. I'd love some use cases :)

**Comment by thomastthai** [comment]
@gedw99 was the person who filed [issue #3](https://github.com/verifa/horizon/issues/3). I was exploring different options for caching to learn, profile, and do tests. They suggested using NATS for caching Go based http servers using templates and HTMX. 

I have been away from the dev and tech community for decades and only recent came back to help lead a project. There is a lot to catch up and I sometimes get lost in the unfamiliar jargons.

We do use Kubernetes and associated infrastructure. If there is a leaner way of accomplishing something, it's worth exploring. I learn best by example, so I look forward to seeing the Greetings example up and running.

**Comment by gedw99** [comment]
Hey all :)

I found 2 good going file caching that does what memcache does with LRU also.

https://github.com/Tochemey/groupcache is pretty new and only a single developer, but looks decent

**Comment by thomastthai** [comment]
@gedw99, that's an excellent find and looks very useful! Thank you for keeping on feeding us useful recommendations! You rock!

**Comment by gedw99** [comment]
I have not had a chance to kick there tires yet, so see how it goes.

**Comment by jlarfors** [comment]
Synadia also just published this video comparing NATS KV with Redis (on a high level), which is very timely: https://www.youtube.com/watch?v=XLJ5_5MsgGQ

Horizon is not supposed to be used as a cache. It is more similar to how Kubernetes stores objects built on top of NATS with some web-stuff for building internal tools to help software development teams. I'd say you can look around for some inspiration on using NATS but that's about it.

**Comment by gedw99** [comment]
thanks @jlarfors  most helpful ! 

I have been using NATS as a redistribution replacement for years.
